export * from './Banner';
export * from './CornerOfferSection';
export * from './ExploreProducts';
export * from './FeatureProducts';
export * from './Newsletter';
export { default as Pagination } from './Pagination';
export * from './ProductReview';
export * from './RecentlyViewed';
export * from './SiteInfo';
export * from './Tab';
export * from './Testimonial';
export * from './placeholders';
